[package]
name = "harlan-boot"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
log = "0.4"
harlan-kernel = { path = "../kernel" }
uefi = { version = "0.40.0", features = ["logger", "log-debugcon"] }
harlan-hal = { path = "../hal" }
harlan-fbcon = { path = "../drivers/fbcon" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
harlan-arch-x86_64 = { path = "../arch/x86_64" }
