[package]
name = "aion-boot"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
log = "0.4"
aion-kernel = { path = "../kernel" }
uefi = { version = "0.40.0", features = ["logger", "log-debugcon"] }
aion-hal = { path = "../hal" }
aion-fbcon = { path = "../drivers/fbcon" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
aion-arch-x86_64 = { path = "../arch/x86_64" }
